spring:
  application:
    name: "spring-app"
    datasource:
      url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sapi
      password:
    h2:
      console:
        enabled: true
